with 

source as (

    select * from {{ source('claims', 'claimdetail') }}

),

renamed as (

    select
        siteid as site_id,
        claimid as claim_id,
        matched_yn as matched_yn,
        primaryclaimid as primary_claim_id,
        priclaimid_rownum as pri_claim_id_rownum,
        rootclaimid as root_claim_id,
        icn as icn,
        bseq as bseq,
        npay as npay,
        linkedclaimtypecode as linked_claim_type_code,
        linkedclaimtypedesc as linked_claim_type_desc,
        billeddate as billed_date,
        importdate as import_date,
        exportdate as export_date,
        stmfrom as stm_from,
        stmthru as stm_thru,
        payerrcvdate as payer_rcv_date,
        claimtypecode as claim_type_code,
        claimtypename as claim_type_name,
        tob as tob,
        tobtype as tob_type,
        tobfacilitytype as tob_facility_type,
        tobclassification as tob_classification,
        tobfrequency as tob_frequency,
        totalcharges as total_charges,
        estamtdue as est_amt_due,
        renderingprovidernpi as rendering_provider_npi,
        renderingprovidernamelast as rendering_provider_name_last,
        renderingprovidernamefirst as rendering_provider_name_first,
        renderingprovidernamemiddle as rendering_provider_name_middle,
        renderingprovidertaxid as rendering_provider_tax_id,
        renderingprovidertaxonomy as rendering_provider_taxonomy,
        attendingphysiciannpi as attending_physician_npi,
        attendingphysicianlastname as attending_physician_last_name,
        attendingphysicianfirstname as attending_physician_first_name,
        attendingphysicianmiddlename as attending_physician_middle_name,
        attendingphysiciantaxonomy as attending_physician_taxonomy,
        operatingphysiciannpi as operating_physician_npi,
        operatingphysicianlastname as operating_physician_last_name,
        operatingphysicianfirstname as operating_physician_first_name,
        operatingphysicianmiddlename as operating_physician_middle_name,
        operatingphysiciantaxonomy as operating_physician_taxonomy,
        otherphysiciannpi as other_physician_npi,
        otherphysicianlastname as other_physician_last_name,
        otherphysicianfirstname as other_physician_first_name,
        otherphysicianmiddlename as other_physician_middle_name,
        otherphysiciantaxonomy as other_physician_taxonomy,
        referringphysiciannpi as referring_physician_npi,
        referringphysicianlastname as referring_physician_last_name,
        referringphysicianfirstname as referring_physician_first_name,
        referringphysicianmiddlename as referring_physician_middle_name,
        referringphysiciantaxonomy as referring_physician_taxonomy,
        payerprimarytypecode as payer_primary_type_code,
        payerprimarytypedesc as payer_primary_type_desc,
        payerprimaryid as payer_primary_id,
        payerprimaryname as payer_primary_name,
        payerprimaryaddress1 as payer_primary_address_1,
        payerprimaryaddress2 as payer_primary_address_2,
        payerprimarycity as payer_primary_city,
        payerprimarystate as payer_primary_state,
        payerprimaryzip as payer_primary_zip,
        payerprimaryplancode as payer_primary_plan_code,
        payersecondarytypecode as payer_secondary_type_code,
        payersecondarytypedesc as payer_secondary_type_desc,
        payersecondaryid as payer_secondary_id,
        payersecondaryname as payer_secondary_name,
        payersecondaryaddress1 as payer_secondary_address_1,
        payersecondaryaddress2 as payer_secondary_address_2,
        payersecondarycity as payer_secondary_city,
        payersecondarystate as payer_secondary_state,
        payersecondaryzip as payer_secondary_zip,
        payersecondaryplancode as payer_secondary_plan_code,
        drgcode as drg_code,
        principalprocedurecode as principal_procedure_code,
        principalproceduredate as principal_procedure_date,
        ubconditioncodes as ub_condition_codes,
        ubocccodes as ub_occ_codes,
        uboccspancodes as ub_occ_span_codes,
        ubvaluecodes as ub_value_codes,
        revcodes as rev_codes,
        primarydiagnosis as primary_diagnosis,
        admittingdiagnosis as admitting_diagnosis,
        icdversion as icd_version,
        primarydiagnosis_poa as primary_diagnosis_poa,
        externalcauseofinjury1 as external_cause_of_injury_1,
        externalcauseofinjury2 as external_cause_of_injury_2,
        externalcauseofinjury3 as external_cause_of_injury_3,
        externalcauseofinjury1_poa as external_cause_of_injury_1_poa,
        externalcauseofinjury2_poa as external_cause_of_injury_2_poa,
        externalcauseofinjury3_poa as external_cause_of_injury_3_poa,
        patintreasonforvisit1 as patient_reason_for_visit_1,
        patintreasonforvisit2 as patient_reason_for_visit_2,
        patintreasonforvisit3 as patient_reason_for_visit_3,
        patient_key as patient_key,
        chargedetailavail_yn as charge_detail_avail_yn,
        uniquepatient_key as unique_patient_key,
        admissionsource as admission_source,
        admissiontype as admission_type,
        dischargestatus as discharge_status,
        providerid as provider_id
    from source

)

select * from renamed
